language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"

install: pip install -r requirements.txt

before_cache:
- rm -f $HOME/.monstercatconnect/connect.cookies

cache:
  directories:
  - "$HOME/.monstercatconnect/"

script:
- python setup_travis.py
- python notifier.py test

env:
  global:
  - secure: FKWjpQ63lLQSoQ6lM41YcYd+gpP9E2OdPDwhLron1SC8I10XIBXoD98Qw7d0mBglk3ZDOHag2v8XCutNPHdZGcfPgE2Q9uRCNjMGnquiLWsb8owsw46C2GH2L6nSCNqUrS+OnYRiLpGbAgIxeBEBArt9Ic6ONpHDl6KdsAMk5OUWNiLRkFFL8hQa+HdRKc26HMP8xUXrRRMd4eZk8SyAPW0GIrnN9eg2rMeangfOsD5D3USuuXwSCHOHUEpHUk96dQs4Qun2hv8ipjjlCZz1z/kD7uQn0/vnXZ+Yeasvofe/yEciw6U7dqHfMzJXHMs1KNBT/oDPHiW5ZV9/EbSUjDQHs064WTceJ5/aTY1Csvq4SS5x/TMrEUSo+3Vy7z/st2sQaaoOfvNIT34p3KVQwdaP3cxHMvv5t6Fes3vF/mXem0geGk6a/ha4SatdTkGci60uojHWOwt9/I1FpsZUj3lxTLHKioBmenTu1USt4P7aVVzpU/CXbfAc8YCTnKHihgUlniTPD2FwiiA4NtdimhjLdYH3I6Rq2n0yw7BDz/KtErQdTU077aiBoisLnVD8YkJ//3Q/ZqgPXAgYvMABHD7XjNWWlNsudF8arbm0Vq6s1fXhc2uC4k66TyQdVvwP1BQxQRTMe+ikh2AXwhjlqOwYz3mQQ213knJ6CqltFAs=
  - secure: m1dV2txToxBtcL4hfn6iOvfUQ5jLUs6TgvPmJpsOw9rI3Einc2gr2+qnRQoGjDM41o4U7cVgKzNKQtNalxBxfYzKsQs625aO4kEMSIaK/0uDQkioLPYeQhPoKAo0zys4LkIOnTbFPsvfYGG5E8DNmMlVGfYTqa1DvCVE3tKElffQ6J6wyIYzsjTz48Qntw4a7M3Wwo9GYG1qaqqVy6bfSl6XUwHlU2IS+98j57cOW1OgVQzDlW3AVGBwDDzvOx35RU5E4a69oaLaARhurzux1PqyoCh7ik+6HqucEdLH56KGaNPLMN5VdPdQPe59r7e8BByMBdUoGa7jw102uiyQto85qmvcMYCyEcZc8E5IVYbhNTu1IAaJuOcT8NXfXz2lrlElpm4DxwAik3+L3VQA6KBSdZPB2YUQs1Al11u4uBcyH8q2DJrdQYuErHCzR9V9MUwQCK/BH2ZlO79RTS43ckNShgLonVRb04TEGKaoJHmpPOkHIUyXc5h399wKSSwVYosNBuBV87HS3IupRo42cmRgG4MXBs7U7OjHHPOHjjC0K7hkserMHCXWILW/hUDCjXbXfmOWXmAju12CvD8oxHaFu5D+6AOe+Mgv2sB9Mrsub5i103prjwHUjLYk+0GIcr+f+7kqPOrMjvVGchgxFhuHQXGfWoH7d7zvgXSalec=
  - secure: 3xCpE4W8s1ZSHicnu6eTNuLvWPrciloyj7mAc0QWDVqjjVJYqnB9/SV0omXR/0jEZAAxt1d97RpPU7tMGMpnYZowwDMU6nX51X4vMLvcF6hZYZqqfSGbGACm4hYybEdnrlQ6kD8tpO9h4ubxFzfnq3jZvUUNyx5S2qwdGlVR1DkkGpbI8/HE6iZw0wxrkIQcvrxcJEOHJnRkhPGtKzJnqGdq7zD3wj5swTOyP53FN6s6RrB1QCCCUbjrsyM76pMI70H9eg13DTJx7B3AFZSjwSG8a5xaVWZHZobMA3/I51fwkeouo+0vCm2LciLB6SDi/eKVetjAPXxUdoOUn5Vzi9Bifa/Wm915gE8AcU2U9iynkPf9QJkEfeUZJRCjPaFYHhkhgLpGC5Vl0gkwSvrIZVpncUfPoDvKNTrEUQHNk6sc0iaJ2ywuhtqYaOl2I35360KhTV0Sd1Cz5SmsbT+cGUXTQ+zlbF7pBPKym9guHagoJtUZgLNHru7ySOehYXassVArMnTBe9HicNNfrpygKWqZA5dYCTtlL6MgF/IV9WtKvn6zGdZqFGKJUS654FnHKNMgaJcEjUm9fk+5FIdxJzDlZFr27kI2SKy6IIom0nM1YeacIOz5YpcAKYNx41JZtQLKZoyJGTPdmhQKgWq9pbMaiqW40UxjXI4xYoLPDr8=
  - secure: GStW6F5suEjJ1YygB/T0ZHM0bJBjYrXia1jXt5ve0jeAJXC8X2imWexEDSbPvKz0Z89UFGZXYyY7YpIfDjnS+UPKBJK2sfQlhdYu0+3EQZX7+KjaOAomXZ141bJ6pyKdi7UbEBAUO4E/gct+9Rlt8Ncd3oCO9zUFmobySZ44nzFhvgQXm9sBJgGo2wEeFC7CJIA3O99hL8zHzX1/xoGt4hlA5gxlsiRHvWuwEcUE/KowfROdLSlzJ+TU8CwZscDpO7F96eYl4t2G6IYLQHBj0VH+rWvAGSguItk8k21wEoGZesxMgwps8XNfem1vaYu3WUTvFblLsMgdmm2FP3r1xq4NLbhjf4rWhKW4As/QGvP1c7Pv8aZodhC8ZX528pQEP0pRlkXUDy4J510H2t58WQwabM/Xd8Kk6i8Kna9kG8bbUBsDLvsk0IjtBrZ3QTt0MlFso3UjfmJ3Rexa83yynzdMjKvIBJ1ZcdR826GVgAZxQpp3L2Gqsb651QCxbujHgO+RuN+Z7jH/3vSzU8K3k8wvaEtWSrSzCpWusohLp8JM5tu0Rr872NCqxy0zrItJ57xHdLTyt3tPntk0Dg07j6/kp0tOOus/wDtjEqhhroD2hyj/8XTwT7ewh2mJ8ycXTXV94vdE4UwnS3NNMe4Bgp/8pkV/JsL0eVYUS8j7G7s=
